-- Phase 4: Subscription lifecycle — cycles and pushback
-- Requires: public.subscriptions exists with (id, status, anchor_date, frequency)

create table if not exists public.subscription_cycles (
  id uuid primary key default gen_random_uuid(),
  subscription_id uuid not null references public.subscriptions(id) on delete cascade,
  status text not null,
  cycle_start_date date,
  cycle_end_date date,
  created_at timestamptz not null default now()
);

alter table public.subscription_cycles
add column if not exists cycle_sequence integer,
add column if not exists pushback_used boolean not null default false,
add column if not exists pushback_window_start date,
add column if not exists pushback_window_end date,
add column if not exists pushback_fee_percent numeric(5,2),
add column if not exists pushback_fee_applied boolean not null default false,
add column if not exists pushback_fee_waived boolean not null default false,
add column if not exists pushback_fee_waived_reason text,
add column if not exists discount_reset_consumed boolean not null default false;

alter table public.subscriptions
add column if not exists discount_reset_required boolean not null default false;

create table if not exists public.subscription_cycle_bookings (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.subscription_cycles(id) on delete restrict,
  booking_id uuid not null references public.bookings(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(cycle_id),
  unique(booking_id)
);

create unique index if not exists subscription_cycles_one_unresolved_idx
on public.subscription_cycles (subscription_id)
where status in ('open','booked');

create unique index if not exists subscription_cycles_sequence_idx
on public.subscription_cycles (subscription_id, cycle_sequence);

create index if not exists subscription_cycles_subscription_status_idx
on public.subscription_cycles (subscription_id, status);

create index if not exists subscription_cycles_open_window_idx
on public.subscription_cycles (status, cycle_end_date);

create index if not exists subscriptions_status_anchor_idx
on public.subscriptions (status, anchor_date);
